export const FETCH_SHIPS = 'FETCH_SHIPS';
export const FETCH_SHIPS_SUCCESS = 'FETCH_SHIPS_SUCCESS';
export const FETCH_SHIPS_ERROR = 'FETCH_SHIPS_ERROR';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELATE_FROM_FAVORITES = 'DELATE_FROM_FAVORITES'
export const RETRIVE_FAVORITES = 'RETRIVE_FAVORITES';

export const SERCH_SHIPS = 'SERCH_SHIPS';
export const STOP_SERCHING_SHIPS = 'STOP_SERCHING_SHIPS';